version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: meu-banco-musical
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha_secreta  # A senha para conectar
      MYSQL_DATABASE: spotifake         # Nome do banco que ser√° criado
    ports:
      - "3306:3306"                     # Porta externa : Porta interna
    volumes:
      # Isso joga seu script para dentro do container e roda ao iniciar
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql