services:
  app-banco:
    image: postgres:15-alpine
    container_name: projeto-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: musical
    ports:
      - "5432:5432" # Libera a porta para o seu DBeaver acessar
    volumes:
      # Roda o schema automaticamente na criação do banco
      - ./db/schema/init.sql:/docker-entrypoint-initdb.d/init.sql
      # Garante a persistência dos dados
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: